### ISSUE TITLE
Support different JVMs when starting Tomcat

### ISSUE THREAD

**Issue by jprusch** [adashen/vscode-tomcat#317]
- VSCode Version: 1.52.1
- OS Version: Microsoft Windows [Version 10.0.17763.437]
- Tomcat Extension Version: 0.11.2

Visual Code supports developing Java apps using different JVMs.

vscode-tomcat should support starting a Tomcat server using different JVMs, too. This is supported by Eclipse using runtime environments. Right now a Java 8 JDK cannot be used to start a Tomcat server, which is sometimes needed for tests and legacy applications.

**Comment by jprusch** [comment]
I did some tests by adding:
```
    "java": {
        "home": "C:\\Java\\jdk-8.0.222"
    }
```
to the workspace settings.json. This is picked up by vscode-tomcat in

https://github.com/adashen/vscode-tomcat/blob/055abf857d856e6d2335c9bacb89bf9e437ef447/src/Utility.ts#L211

but conflicts with the Java Extensions by Redhat.

I suggest an easy fix (not being a TS dev), to pick up a java.tomcat.jvm setting, if available & fallback to workspace java.home, if not set.

**Comment by howlger** [comment]
> ...
> but conflicts with the Java Extensions by Redhat.
> ...

Make sure a matching Java is set in the `.classpath` file (see [these comments on Stack Overflow](https://stackoverflow.com/questions/66223143/javassist-enhancement-failed-for-all-configured-hibernate-mappings?noredirect=1#comment117088737_66223143)).

**Comment by jprusch** [comment]
Hm, The Java Extension by Redhat needs Java 11+. I want to run my Tomcat with a Java 8 JVM. Setting the .classpath doesn't help me, as Tomcat still uses java.home as startup JVM.
I fixed it for myself by modifying Utility.js of this addon:
` 
function getJavaExecutable() {
  let javaPath = '';
  const config = vscode.workspace.getConfiguration('java');
  if (config) {
    javaPath = config.get('tomcat');
    if (javaPath && javaPath != '') {
      return javaPath ? javaPath + '/bin/java' : 'java';
    } else {
      javaPath = config.get('home')
  }
 }
 return javaPath ? javaPath + '/bin/java' : 'java';
}`
and adding "tomcat": "C:\\Java\\jdk-8.0.222" to the java settings.

**Comment by howlger** [comment]
Sure, but it does not matter here. The Java extension requires Java 11+ to run since it's (based on) Eclipse like the Tomcat extension requires Node.js to run. As far as I know, Java 15 is embedded in the current version of the Java extension.

The Java used in the project (the system library of the Java to compile the code and the Java to run your application) is a different thing. Just make sure the Java referenced in the `.classpath` file has been specified in [`java.configuration.runtimes`](https://marketplace.visualstudio.com/items?itemName=redhat.java).
