### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by dsych** [adashen/vscode-tomcat#325]
Hey, thanks a lot for this extension I am enjoying it quite a lot!)
I do have a question, though, is this project still maintained? There are a couple of annoying bugs I needed to manually patch in my local installation and would like to upstream them. However, there has not been a release in more than a year. Any intention of coming back to this project?

**Comment by KoMaBeLu** [comment]
If @adashen  doesn't answer anytime soon, I think it would be in a lot of people's best interest to just fork this project en publish it under a new name, even though that might seem a bit scummy.

A lot of people are actively using (and loving) this extension, it would be such a shame if pull requests which provide useful fixes and features remain open because @adashen is no longer active.

My TS skills are limited but I wouldn't mind maintaining this repo, reviewing and merging pull requests made by the community at the very least.

@adashen if you read this, let us know how you feel about it.

**Comment by Aliang-SEU** [comment]
It seems that this project is not maintained any more.

**Comment by KoMaBeLu** [comment]
I'm gonna fork this and publish it under a new name over the weekend, I'll post updates here.

**Comment by adashen** [comment]
@KoMaBeLu @dsych @Aliang-SEU Thank you very much for the interesting of this extension. Sorry for the late reply and I am not working on this extension now. I will talk to other contributors and figure out the plan. Please stay tuned. Thanks!

**Comment by Eskibear** [comment]
@dsych 
> There are a couple of annoying bugs I needed to manually patch in my local installation and would like to upstream them.

Please go ahead to create issues about those bugs separatedly. It's also appreciated to submit a PR since you already have some patches.

------

@KoMaBeLu 
> it would be such a shame if pull requests which provide useful fixes and features remain open

I just quickly reviewed some PRs:
#318 allows you to specify custom envs by introducing a new setting, fixing a blocking issue that you want to use specific Java runtime to launch your apps.
#306 is a UX change, always requires confirmation to delete a server.
#263 supports to read `.env` files for custom envs. 

After they get merged (esp. #318), I can help to release a new version to unblock your use cases.

> My TS skills are limited but I wouldn't mind maintaining this repo

Contribution is always appreciated to make this extension and the ecosystem better. You don't need anything like a contributor role to make a contribution, please feel free to review the PRs and leave useful comments at any time. 

> I'm gonna fork this and publish it under a new name over the weekend,

I don't suggest to create a new extension if we still have chance to contribute to this one. Multiple extensions in marketplace with identical/similar names makes new users feel confused about which extension to install, not to mention this one is dominating in installation number for the moment.

------

Currently I myself don't have much effort working on this extension. If there's any bug fixing or improvements, please feel free to contribute back, and I can help with the releasing stuffs.

**Comment by KoMaBeLu** [comment]
@Eskibear thanks for getting back, I totally agree with you on not creating needless confusion by forking this repo.

> not to mention this one is dominating in installation number for the moment.

All the more reason for the team here to regularly maintain this, but I will try to do my part in reviewing PR's

**Comment by Eskibear** [comment]
A new version v0.12.0 has been shipped. 
I'm closing this now.
